"""Added PastExchange model

Revision ID: dd40be7acf35
Revises: 
Create Date: 2025-03-24 16:39:45.038782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd40be7acf35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(length=25),
               type_=sa.String(length=25),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(False)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(False)'))
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=25),
               type_=sa.TEXT(length=25),
               existing_nullable=False)

    op.drop_table('past_exchange')
    # ### end Alembic commands ###
